#!/bin/bash

# set up folders

# copy files as templates


mkdir -p ../../modules ../../modules/actions

mkdir -p ../../modules/actions/middleware ../../modules/actions/models
mkdir -p ../../modules/actions/helpers ../../modules/actions/services
mkdir -p ../../modules/actions/controllers

cp routes.js ../../modules/actions/routes.js
cp middleware/format.js ../../modules/actions/middleware
cp middleware/validate.js ../../modules/actions/middleware
cp controllers/TestController.js ../../modules/actions/controllers
cp -R helpers/ ../../modules/actions/helpers
