#!/bin/bash

# sets up folders

# copy files to project route to be used as templates


mkdir -p ../../modules ../../modules/actions

mkdir -p ../../modules/actions/middleware ../../modules/actions/models
mkdir -p ../../modules/actions/helpers ../../modules/actions/services
mkdir -p ../../modules/actions/controllers

cp -n routes.js ../../modules/actions/routes.js
cp -n controllers/TestController.js ../../modules/actions/controllers
cp -Rn helpers/ ../../modules/actions/
